import { Link } from 'react-router-dom'

const highlights = [
  'Faster reviews — customers finish in ~10 seconds instead of 2–3 minutes',
  'Higher conversion — simple checkpoints mean more guests actually submit',
  'Improved Google ranking and local search visibility',
  'Ease of use for both customers and café staff',
  'Reviews written by a professional content team, not AI — for authenticity and Google policy compliance',
]

export default function About() {
  return (
    <>
      <section className="bg-gradient-to-br from-brand-50 via-white to-amber-50/50 py-16 lg:py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="font-display text-4xl font-bold text-gray-900">About Review My Cafe</h1>
          <p className="mt-4 text-lg text-gray-600 leading-relaxed">
            Review My Cafe helps cafés and restaurants get more Google reviews in less time. We built it for busy customers and busy staff—so everyone wins.
          </p>
          <p className="mt-4 text-gray-600 leading-relaxed">
            Our software helps customers post Google reviews in just <strong>10 seconds</strong> instead of the usual 2–3 minutes. When a customer scans your QR code, a web page opens with simple checkpoints: <strong>food quality</strong>, <strong>service</strong>, <strong>ambience/vibe</strong>, and <strong>value for money</strong>. They select options, give a star rating, and click submit. Our backend then posts a proper, human-written review on Google—improving your visibility, local search ranking, and trust.
          </p>
        </div>
      </section>

      <section className="py-16 lg:py-20 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="font-display text-2xl font-bold text-gray-900">What we do</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            The process works through a QR code. When a customer scans it, a web page opens with your café logo at the top and simple checkpoints. The customer selects their experience for food quality, service, ambience/vibe, and value for money, gives a star rating, and clicks submit.
          </p>
          <p className="mt-4 text-gray-600 leading-relaxed">
            After submission, the review is properly posted on Google. Our backend handles all technical work. Based on the selected checkpoints, a <strong>human-friendly and organic</strong> review is generated by our content team—improving your Google visibility, local search ranking, and trust.
          </p>

          <h2 className="font-display text-2xl font-bold text-gray-900 mt-12">Benefits</h2>
          <ul className="mt-4 space-y-2 text-gray-600">
            {highlights.map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-brand-500 mt-0.5">✓</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="font-display text-2xl font-bold text-gray-900 mt-12">Our approach</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            Reviews are written by a <strong>professional content writing team</strong>, not AI. This ensures authenticity and compliance with Google policies—so your business stays in good standing and your reviews look natural to both customers and search engines.
          </p>

          <h2 className="font-display text-2xl font-bold text-gray-900 mt-12">Business model</h2>
          <p className="mt-4 text-gray-600 leading-relaxed">
            We offer a simple <strong>paid subscription</strong> with affordable pricing for cafés and restaurants. You get a dedicated feedback flow, your own branding (including your café logo on the review screen), and support—without long-term lock-in.
          </p>

          <p className="mt-8 text-gray-600 leading-relaxed">
            Our tone is professional and straightforward, suitable for presentations to a café’s tech team or management. If you’d like to see the flow in action or discuss pricing, use the <Link to="/try-demo" className="text-brand-600 font-medium hover:underline">Try Demo</Link> or <Link to="/contact" className="text-brand-600 font-medium hover:underline">Contact</Link> pages.
          </p>
        </div>
      </section>
    </>
  )
}
